In [8]:
import pandas as pd
import sklearn

from sklearn.model_selection import train_test_split

In [2]:
pd.__version__

'2.0.3'

In [11]:
sklearn.__version__

'1.4.2'

In [9]:
x = pd.read_csv('./bases/entradas_breast.csv')
x

radius_mean   texture_mean  ...   symmetry_worst   fractal_dimension_worst
0           17.99          10.38  ...           0.4601                   0.11890
1           20.57          17.77  ...         275.0000                   0.08902
2           19.69          21.25  ...           0.3613                   0.08758
3           11.42          20.38  ...           0.6638                 173.00000
4           20.29          14.34  ...           0.2364                   0.07678
..            ...            ...  ...              ...                       ...
564         21.56          22.39  ...         206.0000                   0.07115
565         20.13          28.25  ...           0.2572                   0.06637
566         16.60          28.08  ...           0.2218                   0.07820
567         20.60          29.33  ...           0.4087                 124.00000
568          7.76          24.54  ...           0.2871                   0.07039

[569 rows x 30 columns]

In [10]:
y = pd.read_csv('./bases/saidas_breast.csv')
y

0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [7]:
x.shape, y.shape

((569, 30), (569, 1))

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

In [12]:
x_train.shape, y_train.shape

((426, 30), (426, 1))

In [15]:
x_test.shape, y_test.shape

((143, 30), (143, 1))

## **Rede Neural**

In [12]:
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, InputLayer

In [20]:
tf.__version__

'2.16.1'

In [43]:
rn = Sequential([
    InputLayer(shape = (30,)),
    Dense(units = 16, activation='relu', kernel_initializer='random_uniform'),
    Dense(units = 16, activation='relu', kernel_initializer='random_uniform'),
    Dense(units=1, activation='sigmoid')
])

In [44]:
rn.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [45]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001, clipvalue=0.5)

In [46]:
rn.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['binary_accuracy'])

In [47]:
rn.fit(x_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - binary_accuracy: 0.6060 - loss: 1.9852
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7285 - loss: 0.5269
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7345 - loss: 0.5271
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7659 - loss: 0.4652
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8514 - loss: 0.3673
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8118 - loss: 0.4625
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - binary_accuracy: 0.8212 - loss: 0.4412
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.8012 - loss: 0.4784
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8400 - loss: 0.3872
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.8875 - loss: 0.3297
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7916 

### **Fazendo as previsões**

In [35]:
prevs = rn.predict(x_test)
prevs = prevs > 0.5

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step  


In [36]:
prevs

array([[ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [

In [37]:
y_test

0
189  1
456  1
535  0
335  0
17   0
..  ..
396  1
27   0
67   1
114  1
495  1

[143 rows x 1 columns]

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [40]:
accuracy_score(y_test, prevs)

0.8251748251748252

In [41]:
confusion_matrix(y_test, prevs)

array([[33, 23],
       [ 2, 85]])

In [48]:
rn.evaluate(x_test, y_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7688 - loss: 1.0659  


[1.3474434614181519, 0.7412587404251099]

### **Visualização dos pesos**

In [59]:
pesos0 = rn.layers[0].get_weights()

In [60]:
len(pesos0[1])

16

In [61]:
len(pesos0[0])

30

In [62]:
pesos1 = rn.layers[1].get_weights()

In [66]:
len(pesos1)

2

In [63]:
pesos2 = rn.layers[2].get_weights()

In [65]:
len(pesos2)

2

### **Cross Validation**

In [9]:
import scikeras

from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras import backend as k

In [68]:
scikeras.__version__

'0.13.0'

In [76]:
def criar_rede():
    k.clear_session()
    rn = Sequential([
        InputLayer(shape = (30,)),
        Dense(units = 16, activation='relu', kernel_initializer='random_uniform'),
        Dense(units = 16, activation='relu', kernel_initializer='random_uniform'),
        Dense(units=1, activation='sigmoid')
    ])
    otimizador = tf.keras.optimizers.Adam(learning_rate=0.001, clipvalue=0.5)
    rn.compile(optimizer=otimizador, loss='binary_crossentropy', metrics=['binary_accuracy'])
    return rn

In [78]:
rn = KerasClassifier(model= criar_rede, epochs = 100, batch_size=10)

In [79]:
results = cross_val_score(estimator=rn, X = x, y = y, cv = 10, scoring='accuracy')

Epoch 1/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - binary_accuracy: 0.5473 - loss: 1.8121
Epoch 2/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.6629 - loss: 0.6111
Epoch 3/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7508 - loss: 0.5462
Epoch 4/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8075 - loss: 0.4301
Epoch 5/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.8057 - loss: 0.4420
Epoch 6/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7941 - loss: 0.4614
Epoch 7/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.8442 - loss: 0.3601
Epoch 8/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.8393 - loss: 0.3592
Epoch 9/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.8654 - loss: 0.3942
Epoch 10/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8552 - loss: 0.3434
Epoch 11/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8756 -

In [80]:
# Sem Dropout
results.mean()

0.8312969924812028

In [81]:
results.std()

0.04009468212041462

In [82]:
import pickle
pickle.dump(results, open('cross_validation.pkl', 'wb'))

In [ ]:
with open('cross_validation.pkl', 'rb') as f:
    results = pickle.load(f)

### **Dropout**

In [5]:
from tensorflow.keras.layers import Dropout

In [13]:
def criar_rede_dropout():
    k.clear_session()
    rn = Sequential([
        InputLayer(shape = (30,)),
        Dense(units = 16, activation='relu', kernel_initializer='random_uniform'),
        Dropout(rate=0.2),
        Dense(units = 16, activation='relu', kernel_initializer='random_uniform'),
        Dropout(rate=0.2),
        Dense(units=1, activation='sigmoid')
    ])
    otimizador = tf.keras.optimizers.Adam(learning_rate=0.001, clipvalue=0.5)
    rn.compile(optimizer=otimizador, loss='binary_crossentropy', metrics=['binary_accuracy'])
    return rn

In [14]:
rn = KerasClassifier(model= criar_rede_dropout, epochs = 100, batch_size=10)

In [16]:
results_dropout = cross_val_score(estimator=rn, X = x, y = y, cv = 10, scoring='accuracy')

Epoch 1/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - binary_accuracy: 0.5062 - loss: 2.4867
Epoch 2/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - binary_accuracy: 0.6659 - loss: 0.6396 
Epoch 3/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.6455 - loss: 0.6591
Epoch 4/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7133 - loss: 0.6020
Epoch 5/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7267 - loss: 0.5178
Epoch 6/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7275 - loss: 0.5680
Epoch 7/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7961 - loss: 0.4888
Epoch 8/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7675 - loss: 0.5509
Epoch 9/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.7614 - loss: 0.5574
Epoch 10/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7395 - loss: 0.7635
Epoch 11/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7935 

In [17]:
results_dropout

array([0.84210526, 0.80701754, 0.84210526, 0.9122807 , 0.85964912,
       0.9122807 , 0.9122807 , 0.96491228, 0.84210526, 0.89285714])

In [18]:
results_dropout.mean()

0.8787593984962406

In [19]:
results_dropout.std()

0.04531530876048114

### **Tuning dos parâmetros**

In [20]:
from sklearn.model_selection import GridSearchCV

In [29]:
def criar_rede_cross_val(optimizer, loss, kernel_initializer, activation, neurons):
    k.clear_session()
    rn = Sequential([
        InputLayer(shape = (30,)),
        Dense(units = neurons, activation=activation, kernel_initializer=kernel_initializer),
        Dropout(rate=0.2),
        Dense(units = neurons, activation=activation, kernel_initializer=kernel_initializer),
        Dropout(rate=0.2),
        Dense(units=1, activation='sigmoid')
    ])
    rn.compile(optimizer=optimizer, loss=loss, metrics=['binary_accuracy'])
    return rn

In [30]:
rn = KerasClassifier(model=criar_rede_cross_val)

In [24]:
# Para não levar muitro tempo de execução, utilizada outra grade de parâmetros
# params = {
#     'batch_size': [10, 30],
#     'epochs': [50, 100],
#     'model__optimizer': ['adam', 'sgd'] ,
#     'model__loss': ['binary_crossentropy', 'hinge'],
#     'model__kernel_initializer': ['random_uniform', 'normal'],
#     'model__activation': ['relu', 'tanh'],
#     'model__neurons': [16, 8]
# }

In [31]:
params = {
    'batch_size': [10, 30],
    'epochs': [50],
    'model__optimizer': ['adam'] ,
    'model__loss': ['binary_crossentropy'],
    'model__kernel_initializer': ['random_uniform', 'normal'],
    'model__activation': ['relu'],
    'model__neurons': [16]
}

In [32]:
gs = GridSearchCV(estimator=rn, param_grid=params, scoring='accuracy', cv=5)

In [33]:
gs.fit(x, y)

Epoch 1/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - binary_accuracy: 0.5067 - loss: 1.6233
Epoch 2/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.5227 - loss: 0.7175
Epoch 3/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6428 - loss: 0.5858
Epoch 4/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6535 - loss: 0.5998
Epoch 5/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.5965 - loss: 0.5962
Epoch 6/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6544 - loss: 0.5231
Epoch 7/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6626 - loss: 0.5110
Epoch 8/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6880 - loss: 0.4988
Epoch 9/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7323 - loss: 0.5032
Epoch 10/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7654 - loss: 0.4545
Epoch 11/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8141 - loss: 0.46

GridSearchCV(cv=5,
             estimator=KerasClassifier(model=<function criar_rede_cross_val at 0x7f5e0d4d16c0>),
             param_grid={'batch_size': [10, 30], 'epochs': [50],
                         'model__activation': ['relu'],
                         'model__kernel_initializer': ['random_uniform',
                                                       'normal'],
                         'model__loss': ['binary_crossentropy'],
                         'model__neurons': [16], 'model__optimizer': ['adam']},
             scoring='accuracy')

In [34]:
best_params = gs.best_params_
best_params

{'batch_size': 10,
 'epochs': 50,
 'model__activation': 'relu',
 'model__kernel_initializer': 'normal',
 'model__loss': 'binary_crossentropy',
 'model__neurons': 16,
 'model__optimizer': 'adam'}

In [35]:
best_score = gs.best_score_
best_score

0.8910883403198261

In [36]:
gs.cv_results_

{'mean_fit_time': array([14.26170263, 16.54871302,  9.66551175,  7.91373858]),
 'std_fit_time': array([0.29826096, 3.67089743, 1.78771383, 0.1332406 ]),
 'mean_score_time': array([0.48106117, 0.30673962, 0.31149068, 0.27834334]),
 'std_score_time': array([0.22152362, 0.05282925, 0.0759278 , 0.04934115]),
 'param_batch_size': masked_array(data=[10, 10, 30, 30],
              mask=[False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_epochs': masked_array(data=[50, 50, 50, 50],
              mask=[False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_model__activation': masked_array(data=['relu', 'relu', 'relu', 'relu'],
              mask=[False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_model__kernel_initializer': masked_array(data=['random_uniform', 'normal', 'random_uniform', 'normal'],
              mask=[False, False, False, False],
        fill_value='?',
             dty

In [37]:
# {'batch_size': 10,
#  'epochs': 50,
#  'model__activation': 'relu',
#  'model__kernel_initializer': 'normal',
#  'model__loss': 'binary_crossentropy',
#  'model__neurons': 16,
#  'model__optimizer': 'adam'}
model = Sequential()
model.add(InputLayer(shape=(30,)))
model.add(Dense(units=16, activation='relu', kernel_initializer='normal'))
model.add(Dropout(rate=0.2))
model.add(Dense(units=16, activation='relu', kernel_initializer='normal'))
model.add(Dropout(rate=0.2))
model.add(Dense(units=1, activation='sigmoid'))

In [38]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['binary_accuracy'])

In [39]:
model.fit(x, y, batch_size=10, epochs=100)

Epoch 1/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - binary_accuracy: 0.5024 - loss: 6.7080
Epoch 2/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.6178 - loss: 1.3193
Epoch 3/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.6395 - loss: 0.9060
Epoch 4/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.6698 - loss: 0.6037
Epoch 5/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.6645 - loss: 0.5996
Epoch 6/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7385 - loss: 0.5196
Epoch 7/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7831 - loss: 0.4841
Epoch 8/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7218 - loss: 0.5143
Epoch 9/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7834 - loss: 0.5461
Epoch 10/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7654 - loss: 0.4732
Epoch 11/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7955 -

In [40]:
import numpy as np

In [41]:
new_register = np.array([[ 15.80,  8.34,   118,   900,  0.10,  0.26,  0.08, 0.134, 0.178,  0.20,
                    0.05,  1098,  0.87,  4500, 145.2, 0.005,  0.04,  0.05, 0.015,  0.03,
                   0.007, 23.15, 16.64, 178.5,  2018,  0.14, 0.185,  0.84,   158, 0.363]])

In [43]:
new_register.shape

(1, 30)

In [44]:
prevs = model.predict(new_register)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 229ms/step


In [45]:
prevs

array([[1.]], dtype=float32)

In [46]:
prevs = prevs > 0.5
prevs

array([[ True]])

In [47]:
if prevs:
    print('Maligno')
else:
    print('Benigno')

Maligno


In [48]:
model.save('models/model_breast.keras')

In [3]:
new_model = tf.keras.models.load_model('models/model_breast.keras')

In [50]:
new_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,357 (9.21 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,572 (6.14 KB)

In [51]:
new_model.predict(new_register)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step


array([[1.]], dtype=float32)

## **Exercício**
Com base nos parâmetros da rede neural que você aprendeu neste módulo, o objetivo é criar um modelo que ultrapasse a precisão de 90%. 
* Deixar a rede neural mais profunda, adicionando mais camadas ocultas (nas aulas nós fizemos os testes com somente duas camadas)
* Quando fizemos o tuning dos parâmetros chegamos a conclusão que os melhores resultados são obtidos se utilizarmos 8 neurônios nas camadas ocultas. Se aumentarmos essa quantidade para 32 será que teremos melhores resultados? E se colocarmos quantidade de neurônios diferentes nas camadas, como por exemplo: 16 neurônios na primeira camada e 8 na segunda?
* Aumentar e/ou diminuir o percentual de neurônios zerados com o dropout  (lembre-se de que quanto maior o percentual, mais a rede neural tem a tendência a entrar no problema do underfitting)
* Testar outras funções de ativação para as camadas ocultas, conforme as mostradas aqui na documentação do Keras
* Testar outras formas para a inicialização dos pesos, conforme mostradas aqui na documentação do Keras
* Testar outros otimizadores, conforme mostrados aqui na documentação do Keras. Após escolher o melhor otimizador, testar a configuração dos parâmetros learning rate , decay  e clipvalue 
* Aumentar o número de épocas, bem como testas outros valores para o batch_size 

In [25]:
import tensorflow as tf

from keras import backend as k
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, InputLayer, Dropout
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import cross_val_score

In [48]:
def criar_rede():
    k.clear_session()
    rn = Sequential([
        InputLayer(shape = (30,)),
        Dense(units = 32, activation='relu', kernel_initializer='random_uniform'),
        Dropout(rate=0.2),
        Dense(units = 16, activation='relu', kernel_initializer='random_uniform'),
        Dropout(rate=0.2),
        Dense(units=1, activation='sigmoid')
    ])
    rn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['binary_accuracy'])
    return rn
rn = KerasClassifier(model= criar_rede, epochs = 100, batch_size=10)
results_homework = cross_val_score(estimator=rn, X = x, y = y, cv = 10, scoring='accuracy')

Epoch 1/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - binary_accuracy: 0.5446 - loss: 2.8221
Epoch 2/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.6547 - loss: 0.6311
Epoch 3/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7017 - loss: 0.5635
Epoch 4/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6840 - loss: 0.5263
Epoch 5/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7890 - loss: 0.4499
Epoch 6/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7670 - loss: 0.4369
Epoch 7/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - binary_accuracy: 0.7922 - loss: 0.4209
Epoch 8/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - binary_accuracy: 0.8038 - loss: 0.4278
Epoch 9/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8662 - loss: 0.3453
Epoch 10/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8564 - loss: 0.3663
Epoch 11/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8572 

In [49]:
results_homework.mean()

0.9016290726817042

In [51]:
results_homework.std()

0.038507081611051264

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [18]:
prevs = rn.predict(x_test)
prevs = prevs > 0.5

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


In [19]:
accuracy_score(prevs, y_test)

0.8741258741258742