In [3]:
import pandas as pd
import numpy as np
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, InputLayer
from tensorflow.keras import utils as np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

2024-09-04 10:01:12.318962: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-04 10:01:12.519859: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-04 10:01:13.406013: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-04 10:01:16.001903: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [30]:
base = pd.read_csv('bases/iris.csv')
base

sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [5]:
x = base.iloc[:, 0:4].values
pd.DataFrame(x)

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [6]:
y = base.iloc[:, 4].values
pd.DataFrame(y)

0
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [7]:
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
y = np_utils.to_categorical(y)
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

In [23]:
x_train.shape, y_train.shape

((112, 4), (112, 3))

In [24]:
x_test.shape, y_test.shape

((38, 4), (38, 3))

In [25]:
model = Sequential()
model.add(InputLayer(shape=(4,)))
model.add(Dense(4, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [26]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 55 (220.00 B)

 Trainable params: 55 (220.00 B)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [28]:
model.fit(x_train, y_train, batch_size=10, epochs=1000)

Epoch 1/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - categorical_accuracy: 0.3678 - loss: 1.1804
Epoch 2/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.2830 - loss: 1.1743 
Epoch 3/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.4093 - loss: 1.1543      
Epoch 4/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.5507 - loss: 1.1249 
Epoch 5/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.5659 - loss: 1.1297 
Epoch 6/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.6698 - loss: 1.1125 
Epoch 7/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.6003 - loss: 1.1176 
Epoch 8/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.6337 - loss: 1.1147 
Epoch 9/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7079 - loss: 1.0889  
Epoch 10/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.6595 - loss: 1.0945 
Epoc

In [29]:
model.evaluate(x_test, y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - categorical_accuracy: 0.9720 - loss: 0.0920  


[0.08680125325918198, 0.9736841917037964]

In [30]:
prevs = model.predict(x_test)
prevs

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step


array([[8.82162021e-06, 9.99878585e-01, 1.12491005e-04],
       [7.59117769e-12, 7.91263208e-03, 9.92087424e-01],
       [9.99953568e-01, 4.63735014e-05, 6.27155830e-22],
       [1.74038195e-09, 4.30348843e-01, 5.69651127e-01],
       [1.94353422e-08, 7.30770171e-01, 2.69229919e-01],
       [1.37450040e-09, 5.21232486e-01, 4.78767544e-01],
       [1.56782194e-13, 4.31622518e-03, 9.95683789e-01],
       [2.40420850e-04, 9.99749899e-01, 9.73761144e-06],
       [2.46166820e-09, 4.32946593e-01, 5.67053497e-01],
       [7.32316204e-12, 3.02605052e-02, 9.69739437e-01],
       [1.56701299e-14, 1.35167176e-03, 9.98648345e-01],
       [9.99971449e-01, 2.84526886e-05, 6.14164389e-22],
       [1.25522639e-11, 3.02398298e-02, 9.69760120e-01],
       [1.24733611e-12, 4.18124720e-03, 9.95818734e-01],
       [1.54039492e-06, 9.99804258e-01, 1.94129170e-04],
       [2.34302235e-04, 9.99764919e-01, 7.83156509e-07],
       [1.76989676e-13, 3.13917990e-03, 9.96860862e-01],
       [9.99972403e-01, 2.74970

In [32]:
prevs = prevs > 0.5
prevs

array([[False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [Fa

In [33]:
y_test2 = [np.argmax(t) for t in y_test]
y_test2

[1,
 2,
 0,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 0,
 2,
 2,
 1,
 1,
 2,
 0,
 0,
 2,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 2,
 2,
 2,
 2,
 0,
 1,
 1,
 1,
 0,
 2,
 1]

In [34]:
prevs2 = [np.argmax(t) for t in prevs]
prevs2

[1,
 2,
 0,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 0,
 2,
 2,
 1,
 1,
 2,
 0,
 0,
 2,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 2,
 2,
 2,
 2,
 0,
 1,
 1,
 1,
 0,
 2,
 1]

In [36]:
accuracy_score(y_test2, prevs2)

0.9736842105263158

In [38]:
confusion_matrix(y_test2, prevs2)

array([[11,  0,  0],
       [ 0, 11,  0],
       [ 0,  1, 15]])

### **Validação cruzada**

In [11]:
from tensorflow.keras import backend as k
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import cross_val_score

In [42]:
def criar_rede():
    k.clear_session()
    rn = Sequential([
        InputLayer(shape=(4,)),
        Dense(units=4, activation='relu'),
        Dense(units=4, activation='relu'),
        Dense(units=3, activation='softmax')
    ])
    rn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])
    return rn

In [46]:
rn = KerasClassifier(model=criar_rede, epochs=250, batch_size=10)
results = cross_val_score(estimator=rn, X=x, y=y, cv=10, scoring='accuracy')

Epoch 1/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - categorical_accuracy: 0.3174 - loss: 1.2413
Epoch 2/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.3391 - loss: 1.1632 
Epoch 3/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.3384 - loss: 1.1475 
Epoch 4/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - categorical_accuracy: 0.3538 - loss: 1.1107
Epoch 5/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - categorical_accuracy: 0.4055 - loss: 1.0567
Epoch 6/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - categorical_accuracy: 0.3313 - loss: 1.0535
Epoch 7/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - categorical_accuracy: 0.3809 - loss: 1.0131
Epoch 8/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - categorical_accuracy: 0.3737 - loss: 1.0116
Epoch 9/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - categorical_accuracy: 0.4467 - loss: 0.9561
Epoch 10/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - categorical_accuracy: 0.3636 - loss: 0.9739
Epoch 11/250
14/14 ━━━━━━━━

In [47]:
results.mean()

0.7

In [48]:
results.std()

0.40688518719112343

### **Grid Search**

In [8]:
from tensorflow.keras.layers import Dropout
from sklearn.model_selection import GridSearchCV

In [9]:
def criar_rede_grid_search(optimizer, kernel_initializer, activation, neurons, dropout):
    k.clear_session()
    rn = Sequential([
        InputLayer(shape = (4,)),
        Dense(units = neurons, activation=activation, kernel_initializer=kernel_initializer),
        Dropout(rate=dropout),
        Dense(units = neurons, activation=activation, kernel_initializer=kernel_initializer),
        Dropout(rate=dropout),
        Dense(units=3, activation='softmax')
    ])
    rn.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return rn

In [12]:
rn = KerasClassifier(model=criar_rede_grid_search, verbose=0)

In [13]:
params = {
    'batch_size': [10, 30],
    'epochs': [150, 200],
    'model__optimizer': ['adam', 'RMSprop'] ,
    'model__kernel_initializer': ['random_uniform', 'glorot_normal'],
    'model__activation': ['relu', 'tanh',],
    'model__neurons': [4, 8, 16],
    'model__dropout': [0.2, 0.3],
}

In [15]:
gs = GridSearchCV(estimator=rn, param_grid=params, scoring='accuracy', cv=5, verbose=3)
gs.fit(x, y)

Fitting 5 folds for each of 192 candidates, totalling 960 fits
[CV 1/5] END batch_size=10, epochs=150, model__activation=relu, model__dropout=0.2, model__kernel_initializer=random_uniform, model__neurons=4, model__optimizer=adam;, score=0.667 total time=  12.3s
[CV 2/5] END batch_size=10, epochs=150, model__activation=relu, model__dropout=0.2, model__kernel_initializer=random_uniform, model__neurons=4, model__optimizer=adam;, score=0.967 total time=  11.1s
[CV 3/5] END batch_size=10, epochs=150, model__activation=relu, model__dropout=0.2, model__kernel_initializer=random_uniform, model__neurons=4, model__optimizer=adam;, score=0.800 total time=  10.2s
[CV 4/5] END batch_size=10, epochs=150, model__activation=relu, model__dropout=0.2, model__kernel_initializer=random_uniform, model__neurons=4, model__optimizer=adam;, score=0.967 total time=  10.1s
[CV 5/5] END batch_size=10, epochs=150, model__activation=relu, model__dropout=0.2, model__kernel_initializer=random_uniform, model__neurons=

GridSearchCV(cv=5,
             estimator=KerasClassifier(model=<function criar_rede_grid_search at 0x722f80bdbbe0>, verbose=0),
             param_grid={'batch_size': [10, 30], 'epochs': [150, 200],
                         'model__activation': ['relu', 'tanh'],
                         'model__dropout': [0.2, 0.3],
                         'model__kernel_initializer': ['random_uniform',
                                                       'glorot_normal'],
                         'model__neurons': [4, 8, 16],
                         'model__optimizer': ['adam', 'RMSprop']},
             scoring='accuracy', verbose=3)

In [16]:
gs.best_score_, gs.best_params_

(0.9866666666666667,
 {'batch_size': 10,
  'epochs': 150,
  'model__activation': 'tanh',
  'model__dropout': 0.2,
  'model__kernel_initializer': 'random_uniform',
  'model__neurons': 16,
  'model__optimizer': 'adam'})

In [18]:
model = Sequential()
model.add(InputLayer(shape=(4,)))
model.add(Dense(units=16, activation='tanh', kernel_initializer='random_uniform'))
model.add(Dropout(rate=0.2))
model.add(Dense(units=8, activation='tanh', kernel_initializer='random_uniform'))
model.add(Dropout(rate=0.2))
model.add(Dense(units=3, activation='softmax'))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(x, y, batch_size=10, epochs=150)

Epoch 1/150
15/15 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.3239 - loss: 1.0940
Epoch 2/150
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3675 - loss: 1.0784 
Epoch 3/150
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3463 - loss: 1.0602 
Epoch 4/150
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5435 - loss: 1.0046 
Epoch 5/150
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6796 - loss: 0.9352 
Epoch 6/150
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6916 - loss: 0.8662
Epoch 7/150
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7025 - loss: 0.7654
Epoch 8/150
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6679 - loss: 0.6840 
Epoch 9/150
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6304 - loss: 0.6278
Epoch 10/150
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7079 - loss: 0.5328 
Epoch 11/150
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7068 - loss: 0.5239  
Epoch 12/150
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - 

In [21]:
with open('models/iris_struture.json', 'w') as json_file:
    json_file.write(model.to_json())

model.save_weights('models/iris_weights.weights.h5')
model.save('models/iris.h5')

In [22]:
from tensorflow.keras.models import load_model
loaded_network = load_model('models/iris.h5')

In [24]:
# Simulação de novo registro
import numpy as np
new_register = np.array([5.8, 3.1, 3.5, 1.9])

In [31]:
prevs = loaded_network.predict(new_register.reshape(1, -1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step


In [28]:
prevs

array([[0.00160052, 0.9948527 , 0.00354667]], dtype=float32)

In [32]:
prevs_labels = prevs.argmax(axis=1)

In [33]:
prevs_labels

array([1])

In [35]:
print(f'A classe é: {le.inverse_transform(prevs_labels)[0]}')

A classe é: Iris-versicolor
