In [4]:
import numpy as np

from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import InputLayer, Input, Dense
from tensorflow.keras import utils as np_utils

In [6]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [7]:
X_train = X_train.astype('float32') / 255
X_test = X_test.astype('float32') / 255

In [5]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [8]:
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)

In [7]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [8]:
y_test

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [10]:
X_train.shape

(60000, 28, 28)

In [9]:
X_train = X_train.reshape(len(X_train), np.prod(X_train.shape[1:]))
X_test = X_test.reshape(len(X_test), np.prod(X_test.shape[1:]))

In [14]:
X_train.shape, X_test.shape

((60000, 784), (10000, 784))

In [10]:
# 784 -> 32 -> 784
autoencoder = Sequential()
autoencoder.add(InputLayer(shape=(X_train.shape[1],)))
autoencoder.add(Dense(units=32, activation='relu'))
autoencoder.add(Dense(units=X_train.shape[1], activation='sigmoid'))
autoencoder.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 32)             │        25,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 784)            │        25,872 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 50,992 (199.19 KB)

 Trainable params: 50,992 (199.19 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
autoencoder.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [12]:
autoencoder.fit(X_train, X_train, epochs=50, batch_size=256, validation_data=(X_test, X_test))

2024-10-21 14:30:56.480097: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.
2024-10-21 14:30:59.325138: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.


Epoch 1/50
232/235 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.0073 - loss: 0.3878

2024-10-21 14:31:08.744443: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 31360000 exceeds 10% of free system memory.
2024-10-21 14:31:08.855292: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 31360000 exceeds 10% of free system memory.


235/235 ━━━━━━━━━━━━━━━━━━━━ 9s 23ms/step - accuracy: 0.0073 - loss: 0.3859 - val_accuracy: 0.0132 - val_loss: 0.1894
Epoch 2/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - accuracy: 0.0124 - loss: 0.1800 - val_accuracy: 0.0132 - val_loss: 0.1523
Epoch 3/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 5s 23ms/step - accuracy: 0.0140 - loss: 0.1477 - val_accuracy: 0.0115 - val_loss: 0.1312
Epoch 4/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - accuracy: 0.0101 - loss: 0.1292 - val_accuracy: 0.0107 - val_loss: 0.1182
Epoch 5/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - accuracy: 0.0104 - loss: 0.1175 - val_accuracy: 0.0114 - val_loss: 0.1097
Epoch 6/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.0109 - loss: 0.1097 - val_accuracy: 0.0119 - val_loss: 0.1042
Epoch 7/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.0109 - loss: 0.1044 - val_accuracy: 0.0118 - val_loss: 0.1003
Epoch 8/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 6s 24ms/step - accuracy: 0.0113 - loss: 0.1009 - val_accuracy: 0.014

In [22]:
autoencoder.layers

[<Dense name=dense, built=True>, <Dense name=dense_1, built=True>]

In [13]:
original_dimentsion = Input(shape=(X_train.shape[1],))
encoded_layer = autoencoder.layers[0]
encoder = Model(original_dimentsion, encoded_layer(original_dimentsion))

In [14]:
codified_train = encoder.predict(X_train)

2024-10-21 14:38:23.049757: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step


In [15]:
codified_test = encoder.predict(X_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step


In [26]:
codified_train.shape, codified_test.shape

((60000, 32), (10000, 32))

# **Classificação**

### Sem redução de dimensionalidade

In [27]:
c1 = Sequential()
c1.add(InputLayer(shape=(784,)))
c1.add(Dense(units=397, activation='relu'))
c1.add(Dense(units=397, activation='relu'))
c1.add(Dense(units=10, activation='softmax'))

c1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

c1.fit(X_train, y_train, batch_size=256, epochs=100, validation_data=(X_test, y_test))

Epoch 1/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - accuracy: 0.8564 - loss: 0.5306 - val_accuracy: 0.9598 - val_loss: 0.1294
Epoch 2/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9691 - loss: 0.1044 - val_accuracy: 0.9735 - val_loss: 0.0855
Epoch 3/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 12s 49ms/step - accuracy: 0.9808 - loss: 0.0638 - val_accuracy: 0.9773 - val_loss: 0.0727
Epoch 4/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9881 - loss: 0.0410 - val_accuracy: 0.9781 - val_loss: 0.0674
Epoch 5/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 7s 30ms/step - accuracy: 0.9897 - loss: 0.0327 - val_accuracy: 0.9802 - val_loss: 0.0664
Epoch 6/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 8s 35ms/step - accuracy: 0.9941 - loss: 0.0198 - val_accuracy: 0.9783 - val_loss: 0.0704
Epoch 7/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 10s 35ms/step - accuracy: 0.9954 - loss: 0.0150 - val_accuracy: 0.9820 - val_loss: 0.0638
Epoch 8/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 8s 33ms/step - accuracy: 0.9968 - loss: 0.01

### Com redução de dimensionalidade

In [16]:
# 32 -> 397 -> 397 -> 10
c2 = Sequential()
c2.add(InputLayer(shape=(32,)))
c2.add(Dense(units=21, activation='relu'))
c2.add(Dense(units=21, activation='relu'))  
c2.add(Dense(units=10, activation='softmax'))

c2.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

c2.fit(codified_train, y_train, batch_size=256, epochs=100, validation_data=(codified_test, y_test))

Epoch 1/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - accuracy: 0.1946 - loss: 4.6448 - val_accuracy: 0.6364 - val_loss: 1.1128
Epoch 2/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.6825 - loss: 0.9721 - val_accuracy: 0.7765 - val_loss: 0.6995
Epoch 3/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - accuracy: 0.7952 - loss: 0.6568 - val_accuracy: 0.8328 - val_loss: 0.5351
Epoch 4/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 6s 24ms/step - accuracy: 0.8392 - loss: 0.5238 - val_accuracy: 0.8572 - val_loss: 0.4592
Epoch 5/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8621 - loss: 0.4593 - val_accuracy: 0.8743 - val_loss: 0.4153
Epoch 6/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8716 - loss: 0.4200 - val_accuracy: 0.8842 - val_loss: 0.3798
Epoch 7/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8841 - loss: 0.3869 - val_accuracy: 0.8902 - val_loss: 0.3541
Epoch 8/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.8900 - loss: 0.3598 - v