In [30]:
import numpy as np
from sklearn.neural_network import BernoulliRBM
from scipy.special import expit

In [5]:
def convert_to_one_hot(data):
    one_hot_data = []
    for entry in data:
        one_hot_entry = []
        for value in entry:
            if value == 1:
                one_hot_entry.extend([1, 0, 0])  # Viu e gostou
            elif value == 2:
                one_hot_entry.extend([0, 1, 0])  # Viu e não gostou
            elif value == 0:
                one_hot_entry.extend([0, 0, 1])  # Não viu
        one_hot_data.append(one_hot_entry)
    return np.array(one_hot_data)

In [2]:
data = np.array([
    [2, 1, 1, 1, 2, 1],
    [1, 1, 2, 1, 1, 1],
    [2, 1, 0, 1, 0, 1],
    [0, 1, 1, 1, 2, 1],
    [1, 1, 2, 1, 2, 1],
    [1, 1, 0, 1, 1, 1],
])

data.shape

(6, 6)

In [3]:
movies = ['Freddy x Jason', 'O Ultimato Bourne', 'Exterminador do Futuro', 
          'Star Trek', 'Norbit', 'Star Wars']

In [6]:
data = convert_to_one_hot(data)

In [19]:
rbm  = BernoulliRBM(n_components=3, learning_rate=0.01, n_iter=1000, verbose=True)
rbm.fit(data)

[BernoulliRBM] Iteration 1, pseudo-likelihood = -12.48, time = 0.00s
[BernoulliRBM] Iteration 2, pseudo-likelihood = -12.35, time = 0.00s
[BernoulliRBM] Iteration 3, pseudo-likelihood = -12.37, time = 0.00s
[BernoulliRBM] Iteration 4, pseudo-likelihood = -12.12, time = 0.00s
[BernoulliRBM] Iteration 5, pseudo-likelihood = -12.09, time = 0.00s
[BernoulliRBM] Iteration 6, pseudo-likelihood = -12.37, time = 0.00s
[BernoulliRBM] Iteration 7, pseudo-likelihood = -12.09, time = 0.00s
[BernoulliRBM] Iteration 8, pseudo-likelihood = -12.16, time = 0.00s
[BernoulliRBM] Iteration 9, pseudo-likelihood = -12.19, time = 0.00s
[BernoulliRBM] Iteration 10, pseudo-likelihood = -11.79, time = 0.00s
[BernoulliRBM] Iteration 11, pseudo-likelihood = -11.30, time = 0.00s
[BernoulliRBM] Iteration 12, pseudo-likelihood = -12.03, time = 0.00s
[BernoulliRBM] Iteration 13, pseudo-likelihood = -11.85, time = 0.00s
[BernoulliRBM] Iteration 14, pseudo-likelihood = -11.52, time = 0.00s
[BernoulliRBM] Iteration 15, 

BernoulliRBM(learning_rate=0.01, n_components=3, n_iter=1000, verbose=True)

In [20]:
rbm.components_

array([[ 0.32850735,  0.01831475, -0.23617838,  0.86127332, -0.71393907,
        -0.7170403 ,  0.06648419,  0.14756621,  0.01796429,  0.85115196,
        -0.73546768, -0.75435356,  0.11661091,  0.27936243, -0.2630503 ,
         0.85295626, -0.72713903, -0.73334688],
       [ 0.33418173,  0.02747134, -0.24238557,  0.90324539, -0.73382196,
        -0.74426843,  0.07348205,  0.14754463,  0.02914669,  0.88520898,
        -0.76330141, -0.74862255,  0.12174551,  0.29678108, -0.25318818,
         0.89195645, -0.74599687, -0.74565492],
       [ 0.3463758 ,  0.02797701, -0.23996841,  0.91769008, -0.75356244,
        -0.74653946,  0.08008714,  0.15426099,  0.03027705,  0.90023935,
        -0.77784336, -0.77428645,  0.12756364,  0.29807191, -0.26704328,
         0.90482459, -0.75479999, -0.75725758]])

In [21]:
rbm.components_.shape

(3, 18)

In [24]:
leonardo = convert_to_one_hot(np.array([[0, 1, 0, 1, 2, 0]]))
leonardo

array([[0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1]])

In [32]:
hidden_activations = rbm.transform(leonardo)

def reconstruct_from_hidden(hidden, rbm):
    # Calcular a ativação das unidades visíveis usando pesos e bias
    visible_activations = np.dot(hidden, rbm.components_) + rbm.intercept_visible_
    # Aplicar a função sigmoide para obter probabilidades
    return expit(visible_activations)

# Reconstruir sugestão com base nas ativações ocultas
suggestions = reconstruct_from_hidden(hidden_activations, rbm)

In [36]:
print("Filmes recomendados para o Leonardo:")
for i in range(len(movies)):
    # Cada filme é representado por 3 valores (ex: [0, 0, 1] significa não viu)
    start_index = i * 3
    if leonardo[0, start_index:start_index + 3].tolist() == [0, 0, 1] and suggestions[0, start_index] > 0.5:
        print(f"Recomendamos o filme '{movies[i]}'.")

Filmes recomendados para o Leonardo:
Recomendamos o filme 'Star Wars'.


In [93]:
import rbm

In [94]:
rbm = rbm.RBM(num_visible=6, num_hidden=3)

In [95]:
base = np.array([
    [0, 1, 1, 1, 0, 1],
    [1, 1, 0, 1, 1, 1],
    [0, 1, 0, 1, 0, 1],
    [0, 1, 1, 1, 0, 1],
    [1, 1, 0, 1, 0, 1],
    [1, 1, 0, 1, 1, 1],
])

base.shape

(6, 6)

In [96]:
rbm.train(base, max_epochs=5000)

Epoch 0: error is 9.073125079630826
Epoch 1: error is 8.643256621054901
Epoch 2: error is 7.979051323222376
Epoch 3: error is 7.833927256093082
Epoch 4: error is 7.187214598899097
Epoch 5: error is 7.082793692958916
Epoch 6: error is 6.612823680602889
Epoch 7: error is 6.121685639783445
Epoch 8: error is 5.891891407356065
Epoch 9: error is 5.590575759429352
Epoch 10: error is 5.449962715451105
Epoch 11: error is 5.234934773863938
Epoch 12: error is 5.449250736452773
Epoch 13: error is 5.027804985799228
Epoch 14: error is 5.252485231116695
Epoch 15: error is 4.869382594001401
Epoch 16: error is 4.758451772187238
Epoch 17: error is 4.790356882632038
Epoch 18: error is 5.011177887428894
Epoch 19: error is 4.585620354396944
Epoch 20: error is 4.793938901624098
Epoch 21: error is 4.746800423942599
Epoch 22: error is 4.593450097335111
Epoch 23: error is 4.559783678755584
Epoch 24: error is 4.422057494172133
Epoch 25: error is 4.395357045809547
Epoch 26: error is 4.44867810231782
Epoch 27: er

In [97]:
rbm.weights, rbm.weights.shape

(array([[ 8.41543464e-01, -1.10850183e+00, -1.03211820e+00,
         -7.42535378e-03],
        [ 1.56814247e+00,  1.69881321e+00,  1.81022455e+00,
         -7.76945607e+00],
        [ 3.57254370e+00,  1.20773816e+00,  1.25232912e+00,
          1.74317997e+00],
        [-2.83362503e-01, -5.34303169e+00, -5.57071252e+00,
          5.92068677e+00],
        [ 3.57711193e+00,  1.23738402e+00,  1.19905454e+00,
          1.76737754e+00],
        [ 1.00759691e-01,  3.45017821e-01,  3.77027836e-01,
         -5.90285312e+00],
        [ 3.60010333e+00,  1.19728605e+00,  1.23317434e+00,
          1.72478304e+00]]),
 (7, 4))

In [98]:
leonardo = np.array([[0, 1, 0, 1, 0, 0]])

In [99]:
rbm.run_visible(leonardo)

array([[1., 1., 1.]])

In [100]:
hidden_layer = rbm.run_visible(leonardo)
suggestion = rbm.run_hidden(hidden_layer)
suggestion

array([[0., 1., 1., 1., 0., 1.]])

In [101]:
for i in range(len(leonardo[0])):
    if leonardo[0, i] == 0 and suggestion[0, i] == 1:
        print(f"Recomendamos o filme '{movies[i]}'.")

Recomendamos o filme 'Exterminador do Futuro'.
Recomendamos o filme 'Star Wars'.
