In [3]:
import numpy as np
import rbm

In [5]:
rbm = rbm.RBM(num_visible=6, num_hidden=2)

In [7]:
base = np.array([[1, 1, 1, 0, 0, 0],
                [1, 0, 1, 0, 0, 0],
                [1, 1, 1, 0, 0, 0],
                [0, 0, 1, 1, 1, 1],
                [0, 0, 1, 1, 0, 1],
                [0, 0, 1, 1, 0, 1]])

base.shape

(6, 6)

In [8]:
movies = ["A bruxa", "Invocação do mal", "O chamado",
          "Se beber não case", "Gente grande", "American pie"]

In [9]:
rbm.train(base, max_epochs=5000)

Epoch 0: error is 9.170505940091417
Epoch 1: error is 8.949318923907695
Epoch 2: error is 8.730577046884562
Epoch 3: error is 8.604540861897258
Epoch 4: error is 8.402177068742327
Epoch 5: error is 8.401122037228738
Epoch 6: error is 8.149953512803883
Epoch 7: error is 8.114671952638178
Epoch 8: error is 8.036115851433788
Epoch 9: error is 7.786563393664036
Epoch 10: error is 7.874624629877228
Epoch 11: error is 7.792662876121965
Epoch 12: error is 7.722103333976519
Epoch 13: error is 7.618072230039747
Epoch 14: error is 7.678306827391298
Epoch 15: error is 7.4078383252433655
Epoch 16: error is 7.60263020917251
Epoch 17: error is 7.183758272497851
Epoch 18: error is 7.180324934429356
Epoch 19: error is 7.389818979241725
Epoch 20: error is 7.327400450859141
Epoch 21: error is 7.2890751160938665
Epoch 22: error is 7.1518289589357344
Epoch 23: error is 7.246316102383798
Epoch 24: error is 7.012364473905928
Epoch 25: error is 7.040334690194157
Epoch 26: error is 7.063253208130082
Epoch 27:

In [10]:
rbm.weights, rbm.weights.shape

(array([[ 2.47737655,  2.36543542,  0.38674848],
        [-1.01518821, -3.25621175,  7.92652406],
        [ 0.18745889, -7.23783936,  3.30502716],
        [ 4.95178807,  3.9421638 ,  1.88286914],
        [ 0.94008379,  3.633076  , -8.22753611],
        [-1.31821954,  0.61336441, -4.54869037],
        [ 0.94519139,  3.62918382, -8.23010896]]),
 (7, 3))

In [15]:
user1 = np.array([[1, 1, 0, 1, 0, 0]])
user2 = np.array([[0, 0, 0, 1, 1, 0]])

In [22]:
rbm.run_visible(user1)

array([[0., 1.]])

In [16]:
rbm.run_visible(user2)

array([[1., 0.]])

In [23]:
hidden_layer = np.array([[0, 1]])
suggestion = rbm.run_hidden(hidden_layer)
suggestion

array([[1., 1., 1., 0., 0., 0.]])

In [25]:
for i in range(len(user1[0])):
    if user1[0, i] == 0 and suggestion[0, i] == 1:
        print(f"Recomendamos o filme '{movies[i]}'.")

Recomendamos o filme 'O chamado'.
